// <auto-generated />
using Bible.Alarm.Shared.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bible.Alarm.DbMigration.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    partial class MediaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.AudioSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseUrlId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrlPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseUrlId");

                    b.ToTable("AudioSources");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.AudioSourceBaseUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AudioSourceBaseUrls");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayLanguageId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("Code", "LanguageId")
                        .IsUnique();

                    b.ToTable("BiblePublications");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BiblePublicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BiblePublicationId", "Number")
                        .IsUnique();

                    b.ToTable("BiblePublicationSections");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BiblePublicationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BiblePublicationSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("BiblePublicationId", "Number")
                        .IsUnique();

                    b.HasIndex("BiblePublicationSectionId", "Number")
                        .IsUnique();

                    b.ToTable("BiblePublicationTracks");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Music.MelodyMusic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DisplayLanguageId");

                    b.ToTable("MelodyMusic");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Music.MusicTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MelodyMusicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VocalMusicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MelodyMusicId");

                    b.HasIndex("SourceId");

                    b.HasIndex("VocalMusicId");

                    b.ToTable("MusicTracks");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Music.VocalMusic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayLanguageId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("Code", "LanguageId")
                        .IsUnique();

                    b.ToTable("VocalMusic");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.AudioSource", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.AudioSourceBaseUrl", "BaseUrlEntity")
                        .WithMany()
                        .HasForeignKey("BaseUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseUrlEntity");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublication", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Language", "DisplayLanguage")
                        .WithMany()
                        .HasForeignKey("DisplayLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bible.Alarm.Shared.Models.Media.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisplayLanguage");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationSection", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublication", "BiblePublication")
                        .WithMany("Sections")
                        .HasForeignKey("BiblePublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BiblePublication");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationTrack", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublication", "Publication")
                        .WithMany("Tracks")
                        .HasForeignKey("BiblePublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationSection", "Section")
                        .WithMany("Tracks")
                        .HasForeignKey("BiblePublicationSectionId");

                    b.HasOne("Bible.Alarm.Shared.Models.Media.AudioSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.Navigation("Publication");

                    b.Navigation("Section");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Music.MelodyMusic", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Language", "DisplayLanguage")
                        .WithMany()
                        .HasForeignKey("DisplayLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisplayLanguage");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Music.MusicTrack", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Music.MelodyMusic", null)
                        .WithMany("Tracks")
                        .HasForeignKey("MelodyMusicId");

                    b.HasOne("Bible.Alarm.Shared.Models.Media.AudioSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.HasOne("Bible.Alarm.Shared.Models.Media.Music.VocalMusic", null)
                        .WithMany("Tracks")
                        .HasForeignKey("VocalMusicId");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Music.VocalMusic", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Language", "DisplayLanguage")
                        .WithMany()
                        .HasForeignKey("DisplayLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bible.Alarm.Shared.Models.Media.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisplayLanguage");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublication", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationSection", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Music.MelodyMusic", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Music.VocalMusic", b =>
                {
                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
