// <auto-generated />
using System;
using Bible.Alarm.Shared.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bible.Alarm.Shared.Database.Migrations.Media
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20251208220000_AddEfAttributesToModels")]
    partial class AddEfAttributesToModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.AudioSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LookUpPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AudioSource");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Bible.BibleBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BibleTranslationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BibleTranslationId");

                    b.HasIndex("BibleTranslationId", "Number")
                        .IsUnique();

                    b.ToTable("BibleBook");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Bible.BibleChapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BibleBookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BibleBookId");

                    b.HasIndex("BibleBookId", "Number")
                        .IsUnique();

                    b.HasIndex("SourceId");

                    b.ToTable("BibleChapter");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Bible.BibleTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code", "LanguageId")
                        .IsUnique();

                    b.HasIndex("DisplayLanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("BibleTranslations");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Music.MelodyMusic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DisplayLanguageId");

                    b.ToTable("MelodyMusic");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Music.MusicTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MelodyMusicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VocalMusicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MelodyMusicId");

                    b.HasIndex("SourceId");

                    b.HasIndex("VocalMusicId");

                    b.ToTable("MusicTrack");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Music.VocalMusic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code", "LanguageId")
                        .IsUnique();

                    b.HasIndex("DisplayLanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("VocalMusic");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Bible.BibleBook", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Bible.BibleTranslation", "BibleTranslation")
                        .WithMany("Books")
                        .HasForeignKey("BibleTranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BibleTranslation");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Bible.BibleChapter", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Bible.BibleBook", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("BibleBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bible.Alarm.Shared.Models.Media.AudioSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.Navigation("Book");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Bible.BibleTranslation", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Language", "DisplayLanguage")
                        .WithMany()
                        .HasForeignKey("DisplayLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bible.Alarm.Shared.Models.Media.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisplayLanguage");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Music.MelodyMusic", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Language", "DisplayLanguage")
                        .WithMany()
                        .HasForeignKey("DisplayLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisplayLanguage");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Music.MusicTrack", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Music.MelodyMusic", null)
                        .WithMany("Tracks")
                        .HasForeignKey("MelodyMusicId");

                    b.HasOne("Bible.Alarm.Shared.Models.Media.AudioSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.HasOne("Bible.Alarm.Shared.Models.Media.Music.VocalMusic", null)
                        .WithMany("Tracks")
                        .HasForeignKey("VocalMusicId");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Music.VocalMusic", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Language", "DisplayLanguage")
                        .WithMany()
                        .HasForeignKey("DisplayLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bible.Alarm.Shared.Models.Media.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisplayLanguage");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Bible.BibleBook", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Bible.BibleTranslation", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Music.MelodyMusic", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Music.VocalMusic", b =>
                {
                    b.Navigation("Tracks");
                });
        }
    }
}

