// <auto-generated />
using Bible.Alarm.Shared.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bible.Alarm.Shared.Database.Migrations.Media
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20260206141813_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.ApiUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathPrefix")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PathPrefix");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("ApiUrls");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVideo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("PublicationCode");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("BiblePublications");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationCategory", b =>
                {
                    b.Property<int>("BiblePublicationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BiblePublicationId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BiblePublicationCategories");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BiblePublicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BiblePublicationId");

                    b.ToTable("BiblePublicationSections");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BiblePublicationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BiblePublicationSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BiblePublicationId", "TrackCode");

                    b.HasIndex("BiblePublicationSectionId", "TrackCode")
                        .IsUnique();

                    b.ToTable("BiblePublicationTracks");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.PublicationLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HarvestType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PublicationCode", "LanguageId", "CategoryId")
                        .IsUnique();

                    b.ToTable("PublicationLanguages");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.SectionLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HarvestType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicationLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PublicationLanguageId");

                    b.HasIndex("PublicationCode", "SectionCode", "LanguageId")
                        .IsUnique();

                    b.ToTable("SectionLanguages");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.UrlParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApiUrlId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BaseUrlId");

                    b.Property<int?>("BiblePublicationTrackId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsQueryParam")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiUrlId");

                    b.HasIndex("BiblePublicationTrackId");

                    b.ToTable("UrlParams");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.CategoryNameByLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("CategoryNamesByLanguage");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("LanguageCode");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCode")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.LanguageNameByLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayLanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "DisplayLanguageCode")
                        .IsUnique();

                    b.ToTable("LanguageNamesByLanguage");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublication", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationCategory", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublication", "BiblePublication")
                        .WithMany("BiblePublicationCategories")
                        .HasForeignKey("BiblePublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bible.Alarm.Shared.Models.Media.Category", "Category")
                        .WithMany("BiblePublicationCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BiblePublication");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationSection", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublication", "BiblePublication")
                        .WithMany("Sections")
                        .HasForeignKey("BiblePublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BiblePublication");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationTrack", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublication", "Publication")
                        .WithMany("Tracks")
                        .HasForeignKey("BiblePublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationSection", "Section")
                        .WithMany("Tracks")
                        .HasForeignKey("BiblePublicationSectionId");

                    b.Navigation("Publication");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.PublicationLanguage", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bible.Alarm.Shared.Models.Media.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.SectionLanguage", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bible.Alarm.Shared.Models.Media.BiblePublications.PublicationLanguage", "PublicationLanguage")
                        .WithMany("SectionLanguages")
                        .HasForeignKey("PublicationLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("PublicationLanguage");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.UrlParam", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.ApiUrl", "ApiUrl")
                        .WithMany("UrlParams")
                        .HasForeignKey("ApiUrlId");

                    b.HasOne("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationTrack", "BiblePublicationTrack")
                        .WithMany("UrlParams")
                        .HasForeignKey("BiblePublicationTrackId");

                    b.Navigation("ApiUrl");

                    b.Navigation("BiblePublicationTrack");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.CategoryNameByLanguage", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Category", "Category")
                        .WithMany("NamesByLanguage")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.LanguageNameByLanguage", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Language", "Language")
                        .WithMany("NamesByDisplayLanguage")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.ApiUrl", b =>
                {
                    b.Navigation("UrlParams");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublication", b =>
                {
                    b.Navigation("BiblePublicationCategories");

                    b.Navigation("Sections");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationSection", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationTrack", b =>
                {
                    b.Navigation("UrlParams");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.PublicationLanguage", b =>
                {
                    b.Navigation("SectionLanguages");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Category", b =>
                {
                    b.Navigation("BiblePublicationCategories");

                    b.Navigation("NamesByLanguage");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Language", b =>
                {
                    b.Navigation("NamesByDisplayLanguage");
                });
#pragma warning restore 612, 618
        }
    }
}
