// <auto-generated />
using Bible.Alarm.Shared.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bible.Alarm.Shared.Database.Migrations.Media
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20260119020700_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BaseUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathPrefix")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PathPrefix");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("ApiUrls");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVideo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LanguageId");

                    b.ToTable("BiblePublications");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BiblePublicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BiblePublicationId");

                    b.ToTable("BiblePublicationSections");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BiblePublicationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BiblePublicationSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BiblePublicationId", "Number");

                    b.HasIndex("BiblePublicationSectionId", "Number")
                        .IsUnique();

                    b.ToTable("BiblePublicationTracks");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.PublicationLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PublicationCode", "LanguageId")
                        .IsUnique();

                    b.ToTable("PublicationLanguages");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.SectionLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicationLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PublicationLanguageId");

                    b.HasIndex("PublicationCode", "SectionCode", "LanguageId")
                        .IsUnique();

                    b.ToTable("SectionLanguages");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.UrlParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseUrlId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BiblePublicationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BiblePublicationSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BiblePublicationTrackId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsQueryParam")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseUrlId");

                    b.HasIndex("BiblePublicationId");

                    b.HasIndex("BiblePublicationSectionId");

                    b.HasIndex("BiblePublicationTrackId");

                    b.ToTable("UrlParams");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublication", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Category", "Category")
                        .WithMany("BiblePublications")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bible.Alarm.Shared.Models.Media.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId");

                    b.Navigation("Category");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationSection", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublication", "BiblePublication")
                        .WithMany("Sections")
                        .HasForeignKey("BiblePublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BiblePublication");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationTrack", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublication", "Publication")
                        .WithMany("Tracks")
                        .HasForeignKey("BiblePublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationSection", "Section")
                        .WithMany("Tracks")
                        .HasForeignKey("BiblePublicationSectionId");

                    b.Navigation("Publication");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.PublicationLanguage", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.SectionLanguage", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bible.Alarm.Shared.Models.Media.BiblePublications.PublicationLanguage", "PublicationLanguage")
                        .WithMany()
                        .HasForeignKey("PublicationLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("PublicationLanguage");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.UrlParam", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Media.BaseUrl", "BaseUrl")
                        .WithMany("UrlParams")
                        .HasForeignKey("BaseUrlId");

                    b.HasOne("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublication", "BiblePublication")
                        .WithMany("UrlParams")
                        .HasForeignKey("BiblePublicationId");

                    b.HasOne("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationSection", "BiblePublicationSection")
                        .WithMany("UrlParams")
                        .HasForeignKey("BiblePublicationSectionId");

                    b.HasOne("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationTrack", "BiblePublicationTrack")
                        .WithMany("UrlParams")
                        .HasForeignKey("BiblePublicationTrackId");

                    b.Navigation("BaseUrl");

                    b.Navigation("BiblePublication");

                    b.Navigation("BiblePublicationSection");

                    b.Navigation("BiblePublicationTrack");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BaseUrl", b =>
                {
                    b.Navigation("UrlParams");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublication", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("Tracks");

                    b.Navigation("UrlParams");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationSection", b =>
                {
                    b.Navigation("Tracks");

                    b.Navigation("UrlParams");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.BiblePublications.BiblePublicationTrack", b =>
                {
                    b.Navigation("UrlParams");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Media.Category", b =>
                {
                    b.Navigation("BiblePublications");
                });
#pragma warning restore 612, 618
        }
    }
}
