// <auto-generated />
using System;
using Bible.Alarm.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bible.Alarm.Services.Infrastructure.Media.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20200407051322_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Bible.Alarm.Models.AudioSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LookUpPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AudioSource");
                });

            modelBuilder.Entity("Bible.Alarm.Models.BibleBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BibleTranslationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BibleTranslationId");

                    b.ToTable("BibleBook");
                });

            modelBuilder.Entity("Bible.Alarm.Models.BibleChapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BibleBookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BibleBookId");

                    b.HasIndex("SourceId");

                    b.ToTable("BibleChapter");
                });

            modelBuilder.Entity("Bible.Alarm.Models.BibleTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayLanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("BibleTranslations");
                });

            modelBuilder.Entity("Bible.Alarm.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Bible.Alarm.Models.MelodyMusic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayLanguageId");

                    b.ToTable("MelodyMusic");
                });

            modelBuilder.Entity("Bible.Alarm.Models.MusicTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MelodyMusicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VocalMusicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MelodyMusicId");

                    b.HasIndex("SourceId");

                    b.HasIndex("VocalMusicId");

                    b.ToTable("MusicTrack");
                });

            modelBuilder.Entity("Bible.Alarm.Models.VocalMusic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayLanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("VocalMusic");
                });

            modelBuilder.Entity("Bible.Alarm.Models.BibleBook", b =>
                {
                    b.HasOne("Bible.Alarm.Models.BibleTranslation", "BibleTranslation")
                        .WithMany("Books")
                        .HasForeignKey("BibleTranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bible.Alarm.Models.BibleChapter", b =>
                {
                    b.HasOne("Bible.Alarm.Models.BibleBook", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("BibleBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bible.Alarm.Models.AudioSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");
                });

            modelBuilder.Entity("Bible.Alarm.Models.BibleTranslation", b =>
                {
                    b.HasOne("Bible.Alarm.Models.Language", "DisplayLanguage")
                        .WithMany()
                        .HasForeignKey("DisplayLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bible.Alarm.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bible.Alarm.Models.MelodyMusic", b =>
                {
                    b.HasOne("Bible.Alarm.Models.Language", "DisplayLanguage")
                        .WithMany()
                        .HasForeignKey("DisplayLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bible.Alarm.Models.MusicTrack", b =>
                {
                    b.HasOne("Bible.Alarm.Models.MelodyMusic", null)
                        .WithMany("Tracks")
                        .HasForeignKey("MelodyMusicId");

                    b.HasOne("Bible.Alarm.Models.AudioSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.HasOne("Bible.Alarm.Models.VocalMusic", null)
                        .WithMany("Tracks")
                        .HasForeignKey("VocalMusicId");
                });

            modelBuilder.Entity("Bible.Alarm.Models.VocalMusic", b =>
                {
                    b.HasOne("Bible.Alarm.Models.Language", "DisplayLanguage")
                        .WithMany()
                        .HasForeignKey("DisplayLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bible.Alarm.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
