// <auto-generated />
using System;
using Bible.Alarm.Shared.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bible.Alarm.Shared.Database.Migrations.Schedule
{
    [DbContext(typeof(ScheduleDbContext))]
    partial class ScheduleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Schedule.AlarmMusic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlarmScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Repeat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectionCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlarmScheduleId")
                        .IsUnique();

                    b.HasIndex("PublicationCode", "LanguageCode");

                    b.ToTable("AlarmMusic");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Schedule.AlarmNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlarmScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CancellationRequested")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Fired")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlarmScheduleId");

                    b.HasIndex("ScheduledTime");

                    b.HasIndex("Sent", "Fired");

                    b.ToTable("AlarmNotifications");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Schedule.AlarmSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlwaysPlayFromStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentPlayItem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hour")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LatestAlarmNotificationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minute")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MusicEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificationEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfTracksToPlay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Second")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SnoozeMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Hour", "Minute");

                    b.ToTable("AlarmSchedules");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Schedule.BiblePublicationSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlarmScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("FinishedDuration")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SectionCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlarmScheduleId")
                        .IsUnique();

                    b.HasIndex("PublicationCode", "LanguageCode");

                    b.ToTable("BiblePublicationSchedules");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Schedule.GeneralSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("GeneralSettings");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Schedule.AlarmMusic", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Schedule.AlarmSchedule", "AlarmSchedule")
                        .WithOne("Music")
                        .HasForeignKey("Bible.Alarm.Shared.Models.Schedule.AlarmMusic", "AlarmScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlarmSchedule");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Schedule.AlarmNotification", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Schedule.AlarmSchedule", "AlarmSchedule")
                        .WithMany("AlarmNotifications")
                        .HasForeignKey("AlarmScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlarmSchedule");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Schedule.BiblePublicationSchedule", b =>
                {
                    b.HasOne("Bible.Alarm.Shared.Models.Schedule.AlarmSchedule", "AlarmSchedule")
                        .WithOne("BiblePublicationSchedule")
                        .HasForeignKey("Bible.Alarm.Shared.Models.Schedule.BiblePublicationSchedule", "AlarmScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlarmSchedule");
                });

            modelBuilder.Entity("Bible.Alarm.Shared.Models.Schedule.AlarmSchedule", b =>
                {
                    b.Navigation("AlarmNotifications");

                    b.Navigation("BiblePublicationSchedule");

                    b.Navigation("Music");
                });
#pragma warning restore 612, 618
        }
    }
}
